services:
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    env_file:
      - .env
    command: postgres -c listen_addresses='*'
    volumes:
      - /Users/zubinpratap/.chainlink-goerli/pg-data:/var/lib/postgresql/data/
  chainlink:
    image: "smartcontract/chainlink:1.7.0-root"
    env_file:
      - .env
    depends_on:
      - postgres
    restart: on-failure:5
    ports:
      - "6688:6688"
    volumes:
      - /Users/zubinpratap/.chainlink-goerli/chainlink-data:/chainlink/
    command: node start --password /chainlink-data/password --api /chainlink-data/apicredentials
